export const ItalyRegions = <>
<option value="Abruzzo">Abruzzo</option>
<option value="Aosta Valley">Aosta Valley</option>
<option value="Apulia">Apulia</option>
<option value="Basilicata">Basilicata</option>
<option value="Calabria">Calabria</option>
<option value="Campania">Campania</option>
<option value="Emilia-Romagna">Emilia-Romagna</option>
<option value="Friuli-Venezia Giulia">Friuli-Venezia Giulia</option>
<option value="Lazio">Lazio</option>
<option value="Liguria">Liguria</option>
<option value="Lombardy">Lombardy</option>
<option value="Marche">Marche</option>
<option value="Molise">Molise</option>
<option value="Piedmont">Piedmont</option>
<option value="Sardinia">Sardinia</option>
<option value="Sicily">Sicily</option>
<option value="Trentino-Alto Adige/Südtirol">Trentino-Alto Adige/Südtirol</option>
<option value="Tuscany">Tuscany</option>
<option value="Umbria">Umbria</option>
<option value="Veneto">Veneto</option>
</>