export const Breeds = {
    MixedBreed: 'Mixed breed',
    Affenpinscher: 'Affenpinscher',
    AfghanHound: 'Afghan Hound',
    AiredaleTerrier: 'Airedale Terrier',
    Akita: 'Akita',
    AlaskanMalamute: 'Alaskan Malamute',
    AmericanBulldog: 'American Bulldog',
    AmericanCockerSpaniel: 'American Cocker Spaniel',
    AmericanEnglishCoonhound: 'American English Coonhound',
    AmericanEskimoDog: 'American Eskimo Dog',
    AmericanFoxhound: 'American Foxhound',
    AmericanHairlessTerrier: 'American Hairless Terrier',
    AmericanLeopardHound: 'American Leopard Hound',
    AmericanPitBullTerrier: 'American Pit Bull Terrier',
    AmericanStaffordshireTerrier: 'American Staffordshire Terrier',
    AmericanWaterSpaniel: 'American Water Spaniel',
    AnatolianShepherdDog: 'Anatolian Shepherd Dog',
    AppenzellerSennenhund: 'Appenzeller Sennenhund',
    AustralianCattleDog: 'Australian Cattle Dog',
    AustralianKelpie: 'Australian Kelpie',
    AustralianShepherd: 'Australian Shepherd',
    AustralianTerrier: 'Australian Terrier',
    Azawakh: 'Azawakh',
    Barbet: 'Barbet',
    Basenji: 'Basenji',
    BassetHound: 'Basset Hound',
    Beagle: 'Beagle',
    BeardedCollie: 'Bearded Collie',
    Beauceron: 'Beauceron',
    BedlingtonTerrier: 'Bedlington Terrier',
    BelgianLaekenois: 'Belgian Laekenois',
    BelgianMalinois: 'Belgian Malinois',
    BelgianSheepdog: 'Belgian Sheepdog',
    BelgianTervuren: 'Belgian Tervuren',
    BergerPicard: 'Berger Picard',
    BerneseMountainDog: 'Bernese Mountain Dog',
    BichonFrise: 'Bichon Frise',
    BlackAndTanCoonhound: 'Black and Tan Coonhound',
    BlackRussianTerrier: 'Black Russian Terrier',
    Bloodhound: 'Bloodhound',
    BluetickCoonhound: 'Bluetick Coonhound',
    Bolognese: 'Bolognese',
    BorderCollie: 'Border Collie',
    BorderTerrier: 'Border Terrier',
    Borzoi: 'Borzoi',
    BostonTerrier: 'Boston Terrier',
    BouvierdesFlandres: 'Bouvier des Flandres',
    Boxer: 'Boxer',
    BoykinSpaniel: 'Boykin Spaniel',
    BraccoItaliano: 'Bracco Italiano',
    Briard: 'Briard',
    Brittany: 'Brittany',
    BrusselsGriffon: 'Brussels Griffon',
    BullTerrier: 'Bull Terrier',
    Bulldog: 'Bulldog',
    Bullmastiff: 'Bullmastiff',
    CairnTerrier: 'Cairn Terrier',
    CanaanDog: 'Canaan Dog',
    CaneCorso: 'Cane Corso',
    CardiganWelshCorgi: 'Cardigan Welsh Corgi',
    CavalierKingCharlesSpaniel: 'Cavalier King Charles Spaniel',
    CeskyTerrier: 'Cesky Terrier',
    ChesapeakeBayRetriever: 'Chesapeake Bay Retriever',
    Chihuahua: 'Chihuahua',
    ChineseCrested: 'Chinese Crested',
    ChineseSharPei: 'Chinese Shar-Pei',
    Chinook: 'Chinook',
    ChowChow: 'Chow Chow',
    CirnecoDellEtna: 'Cirneco dell’Etna',
    ClumberSpaniel: 'Clumber Spaniel',
    Cockapoo: 'Cockapoo',
    CockerSpaniel: 'Cocker Spaniel',
    Collie: 'Collie',
    CotondeTulear: 'Coton de Tulear',
    CurlyCoatedRetriever: 'Curly-Coated Retriever',
    Dachshund: 'Dachshund',
    Dalmatian: 'Dalmatian',
    DandieDinmontTerrier: 'Dandie Dinmont Terrier',
    DobermanPinscher: 'Doberman Pinscher',
    DogoArgentino: 'Dogo Argentino',
    DoguedeBordeaux: 'Dogue de Bordeaux',
    DutchShepherd: 'Dutch Shepherd',
    EnglishCockerSpaniel: 'English Cocker Spaniel',
    EnglishFoxhound: 'English Foxhound',
    EnglishSetter: 'English Setter',
    EnglishSpringerSpaniel: 'English Springer Spaniel',
    EnglishToySpaniel: 'English Toy Spaniel',
    EntlebucherMountainDog: 'Entlebucher Mountain Dog',
    EskimoDog: 'Eskimo Dog',
    EstrelaMountainDog: 'Estrela Mountain Dog',
    FieldSpaniel: 'Field Spaniel',
    FinnishLapphund: 'Finnish Lapphund',
    FinnishSpitz: 'Finnish Spitz',
    FlatCoatedRetriever: 'Flat-Coated Retriever',
    FrenchBulldog: 'French Bulldog',
    GermanPinscher: 'German Pinscher',
    GermanShepherdDog: 'German Shepherd Dog',
    GermanShorthairedPointer: 'German Shorthaired Pointer',
    GermanWirehairedPointer: 'German Wirehaired Pointer',
    GiantSchnauzer: 'Giant Schnauzer',
    GlenofImaalTerrier: 'Glen of Imaal Terrier',
    Goldador: 'Goldador',
    GoldenRetriever: 'Golden Retriever',
    Goldendoodle: 'Goldendoodle',
    GordonSetter: 'Gordon Setter',
    GrandBassetGriffonVendeen: 'Grand Basset Griffon Vendeen',
    GreatDane: 'Great Dane',
    GreatPyrenees: 'Great Pyrenees',
    GreaterSwissMountainDog: 'Greater Swiss Mountain Dog',
    Greyhound: 'Greyhound',
    Harrier: 'Harrier',
    Havanese: 'Havanese',
    Hovawart: 'Hovawart',
    IbizanHound: 'Ibizan Hound',
    IcelandicSheepdog: 'Icelandic Sheepdog',
    IrishRedandWhiteSetter: 'Irish Red and White Setter',
    IrishSetter: 'Irish Setter',
    IrishTerrier: 'Irish Terrier',
    IrishWaterSpaniel: 'Irish Water Spaniel',
    IrishWolfhound: 'Irish Wolfhound',
    ItalianGreyhound: 'Italian Greyhound',
    JackRussellTerrier: 'Jack Russell Terrier',
    JapaneseChin: 'Japanese Chin',
    JapaneseSpitz: 'Japanese Spitz',
    Keeshond: 'Keeshond',
    KerryBlueTerrier: 'Kerry Blue Terrier',
    KingCharlesSpaniel: 'King Charles Spaniel',
    Komondor: 'Komondor',
    Kooikerhondje: 'Kooikerhondje',
    Kuvasz: 'Kuvasz',
    Labradoodle: 'Labradoodle',
    LabradorRetriever: 'Labrador Retriever',
    LagottoRomagnolo: 'Lagotto Romagnolo',
    LakelandTerrier: 'Lakeland Terrier',
    LancashireHeeler: 'Lancashire Heeler',
    Leonberger: 'Leonberger',
    LhasaApso: 'Lhasa Apso',
    Lowchen: 'Lowchen',
    Maltese: 'Maltese',
    MalteseShihTzu: 'Maltese Shih Tzu',
    ManchesterTerrier: 'Manchester Terrier',
    MaremmaSheepdog: 'Maremma Sheepdog',
    Mastiff: 'Mastiff',
    MiniatureBullTerrier: 'Miniature Bull Terrier',
    MiniaturePinscher: 'Miniature Pinscher',
    MiniatureSchnauzer: 'Miniature Schnauzer',
    Newfoundland: 'Newfoundland',
    NorfolkTerrier: 'Norfolk Terrier',
    NorwegianBuhund: 'Norwegian Buhund',
    NorwegianElkhound: 'Norwegian Elkhound',
    NorwegianLundehund: 'Norwegian Lundehund',
    NorwichTerrier: 'Norwich Terrier',
    NovaScotiaDuckTollingRetriever: 'Nova Scotia Duck Tolling Retriever',
    OldEnglishSheepdog: 'Old English Sheepdog',
    Otterhound: 'Otterhound',
    Papillon: 'Papillon',
    Pekingese: 'Pekingese',
    PembrokeWelshCorgi: 'Pembroke Welsh Corgi',
    PetitBassetGriffonVendeen: 'Petit Basset Griffon Vendeen',
    PharaohHound: 'Pharaoh Hound',
    Plott: 'Plott',
    Pointer: 'Pointer',
    PolishLowlandSheepdog: 'Polish Lowland Sheepdog',
    Pomeranian: 'Pomeranian',
    Poodle: 'Poodle',
    PortuguesePodengoPequeno: 'Portuguese Podengo Pequeno',
    PortugueseWaterDog: 'Portuguese Water Dog',
    Pug: 'Pug',
    Puli: 'Puli',
    Pumi: 'Pumi',
    PyreneanShepherd: 'Pyrenean Shepherd',
    RatTerrier: 'Rat Terrier',
    RedboneCoonhound: 'Redbone Coonhound',
    RhodesianRidgeback: 'Rhodesian Ridgeback',
    Rottweiler: 'Rottweiler',
    RussellTerrier: 'Russell Terrier',
    SaintBernard: 'Saint Bernard',
    Saluki: 'Saluki',
    Samoyed: 'Samoyed',
    Schipperke: 'Schipperke',
    ScottishDeerhound: 'Scottish Deerhound',
    ScottishTerrier: 'Scottish Terrier',
    SealyhamTerrier: 'Sealyham Terrier',
    ShetlandSheepdog: 'Shetland Sheepdog',
    ShibaInu: 'Shiba Inu',
    ShihTzu: 'Shih Tzu',
    SiberianHusky: 'Siberian Husky',
    SilkyTerrier: 'Silky Terrier',
    SkyeTerrier: 'Skye Terrier',
    Sloughi: 'Sloughi',
    SmallMunsterlanderPointer: 'Small Munsterlander Pointer',
    SoftCoatedWheatenTerrier: 'Soft-Coated Wheaten Terrier',
    SpanishWaterDog: 'Spanish Water Dog',
    SpinoneItaliano: 'Spinone Italiano',
    StaffordshireBullTerrier: 'Staffordshire Bull Terrier',
    StandardSchnauzer: 'Standard Schnauzer',
    SussexSpaniel: 'Sussex Spaniel',
    SwedishLapphund: 'Swedish Lapphund',
    SwedishVallhund: 'Swedish Vallhund',
    TibetanMastiff: 'Tibetan Mastiff',
    TibetanSpaniel: 'Tibetan Spaniel',
    TibetanTerrier: 'Tibetan Terrier',
    ToyFoxTerrier: 'Toy Fox Terrier',
    TreeingTennesseeBrindle: 'Treeing Tennessee Brindle',
    TreeingWalkerCoonhound: 'Treeing Walker Coonhound',
    Vizsla: 'Vizsla',
    Weimaraner: 'Weimaraner',
    WelshSpringerSpaniel: 'Welsh Springer Spaniel',
    WelshTerrier: 'Welsh Terrier',
    WestHighlandWhiteTerrier: 'West Highland White Terrier',
    Whippet: 'Whippet',
    WireFoxTerrier: 'Wire Fox Terrier',
    WirehairedPointingGriffon: 'Wirehaired Pointing Griffon',
    WirehairedVizsla: 'Wirehaired Vizsla',
    Xoloitzcuintli: 'Xoloitzcuintli',
    YorkshireTerrier: 'Yorkshire Terrier'
  }
  